### ISSUE TITLE
Редактирование пользовательских историй

### ISSUE THREAD

**Issue by itSveta** [itSveta/Learn3D#13]
- Убрать пользователи, университет, добавить студента, преподавателя и выпускающую кафедру (администрацию).Стейкхолдер — это личность, мнение о проекте которой невозможно проигнорировать.
- Провести опрос у студентов и преподавателей.
- Выяснить, что каждый ждет от проекта, что не устраивает в проведении занятий в настоящий момент.

**Comment by TrinaRina** [comment]
![image](https://user-images.githubusercontent.com/63111924/117457334-cbb85880-af51-11eb-8246-8fb3d4a814a5.png)
