### ISSUE TITLE
Разработка прототипов

### ISSUE THREAD

**Issue by itSveta** [itSveta/Learn3D#18]
-  Доработать существующие части прототипов;
- Доделать оставшиеся интерфейсы.

**Comment by itSveta** [comment]
Наша система = загрузка и обзор 3д моделей.

**Comment by MyDanielM** [comment]
https://www.figma.com/file/CqBlCQs8JGsOk9yFv7UmBb/%D0%9F%D1%80%D0%B0%D0%BA%D1%82%D0%B8%D0%BA%D0%B0-2020?node-id=370%3A16

**Comment by MyDanielM** [comment]
Потребовалась доработка прототипов

**Comment by MyDanielM** [comment]
https://www.figma.com/proto/OY5lYmIPZ00QLFLMRFVlra/%D0%9F%D1%80%D0%BE%D1%82%D0%BE%D1%82%D0%B8%D0%BF?page-id=0%3A1&node-id=0%3A70&viewport=761%2C456%2C0.05806678906083107&scaling=min-zoom
