### ISSUE TITLE
Исправление ошибок в виденье продукта

### ISSUE THREAD

**Issue by itSveta** [itSveta/Learn3D#7]
Внести изменения в соответствии с командным обсуждением в Product Vision, Biz Vision

**Comment by itSveta** [comment]
Наш продукт не меняет подачу материала, а позволяет в игровой форме оценить свои модели и модели др. студентов.

**Comment by TrinaRina** [comment]
![image](https://user-images.githubusercontent.com/63111924/117566156-ac3e3e80-b0bd-11eb-9f3c-8d9dfac8c629.png)
![image](https://user-images.githubusercontent.com/63111924/117566218-0a6b2180-b0be-11eb-8809-20db5467f154.png)
